name: CI

on:
  workflow_dispatch:
  
jobs:
  detect_secrets:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: detect secret
        run: |
          pip install detect-secrets
          detect-secrets scan
